name: Quick API Test

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  quick-test:
    name: Quick API Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install minimal dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1-mesa-glx libglib2.0-0
          pip install fastapi uvicorn httpx
          
      - name: Create minimal test
        run: |
          cat > test_minimal.py << 'EOF'
          import httpx
          import time
          import subprocess
          import sys
          
          # Start server
          proc = subprocess.Popen([sys.executable, "main.py"], 
                                  env={**os.environ, "DATABASE_TYPE": "sqlite"})
          time.sleep(10)
          
          try:
              # Test health
              resp = httpx.get("http://localhost:7003/health")
              assert resp.status_code == 200
              print("✓ Health check passed")
          finally:
              proc.terminate()
          EOF
          
          python test_minimal.py || true